name: voting_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  firebase_core: ^2.29.0
  firebase_messaging: ^14.8.1
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.2.1
  overlay_support: ^2.1.0
  postgres: ^3.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
